# Title: Snakefile
# Author: Amanda Zacharias
# Date: 2023-06-01
# Email: 16amz1@queensu.ca
#-------------------------------------------------
# Notes -------------------------------------------
# source activate ~/mareesTutorialGWAS/workflow/envs/mareesGWAS
# module load StdEnv/2020 python/3.11.2
# Example executions:
# snakemake --cores 1 --use-conda
# snakemake --slurm --jobs 2 --use-conda
# snakemake --slurm --jobs 10 --rerun-incomplete --use-conda
# Visualize dag: 
# snakemake --dag | dot -Tpdf > dag.pdf

# Load packages
import os
from os.path import join

# Load rules
include: join("rules", "1.1missing.smk")
include: join("rules", "1.2checkSex.smk")
include: join("rules", "1.3autoMAF.smk")
include: join("rules", "1.4hwe.smk")
include: join("rules", "1.5het.smk")
include: join("rules", "1.6rel.smk")

rule all:
    input:
        expand(join("results", "1_qcGWAS", "6_rel", "HapMap_rmMissRel.{end}"), 
          end = ["bed", "bim", "fam"])
